# Generated by Django 4.2.10 on 2024-03-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_testmode_delete_testmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestMode',
            new_name='TestModel',
        ),
    ]
